// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmaguciaiInfrastructure.Data;

#nullable disable

namespace SmaguciaiInfrastructure.Migrations
{
    [DbContext(typeof(SmaguciaiDataContext))]
    [Migration("20231117152724_AddCatAndManTable")]
    partial class AddCatAndManTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmaguciaiDomain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountOfProducts")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SmaguciaiDomain.Entities.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c478326-a017-4aee-913b-110425fdc467"),
                            GenderName = "Man"
                        },
                        new
                        {
                            Id = new Guid("07e2e974-4cd2-46dc-bf11-a3cda762b8bd"),
                            GenderName = "Women"
                        },
                        new
                        {
                            Id = new Guid("cf74494a-65cf-4904-a6ea-1d7f3bd1165b"),
                            GenderName = "Unisex"
                        },
                        new
                        {
                            Id = new Guid("a0d8117e-74eb-43a3-8be0-00db445594f2"),
                            GenderName = "Man"
                        },
                        new
                        {
                            Id = new Guid("859b3bd9-617b-49be-9cb1-33df35f226a7"),
                            GenderName = "Women"
                        },
                        new
                        {
                            Id = new Guid("acb6a1c7-7338-4ccb-a50f-24f454dc7550"),
                            GenderName = "Unisex"
                        },
                        new
                        {
                            Id = new Guid("31f9f9d2-4392-4704-9102-b316c242f5f5"),
                            GenderName = "Man"
                        },
                        new
                        {
                            Id = new Guid("e17b3bf9-63ff-4cc4-90f9-6c3d7c3ca7af"),
                            GenderName = "Women"
                        },
                        new
                        {
                            Id = new Guid("4731e42d-813a-4f45-92f4-ecf85ec9b2ad"),
                            GenderName = "Unisex"
                        },
                        new
                        {
                            Id = new Guid("1b859571-f8fb-43ae-ba63-40ccc8925974"),
                            GenderName = "Man"
                        },
                        new
                        {
                            Id = new Guid("7cf34690-1b62-4bb7-9b14-c458b9ae2184"),
                            GenderName = "Women"
                        },
                        new
                        {
                            Id = new Guid("1645fe7c-d405-4523-a4c0-3e9d99e06cd8"),
                            GenderName = "Unisex"
                        },
                        new
                        {
                            Id = new Guid("6df58bf0-10d5-45f4-b0e4-eb89fdc2f86c"),
                            GenderName = "Man"
                        },
                        new
                        {
                            Id = new Guid("a6e632cf-1097-4ec3-b66b-ba47e727ee14"),
                            GenderName = "Women"
                        },
                        new
                        {
                            Id = new Guid("85cb5ee7-1dd2-4ede-8d49-27130b3922ae"),
                            GenderName = "Unisex"
                        });
                });

            modelBuilder.Entity("SmaguciaiDomain.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AmountOfProducts")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("SmaguciaiDomain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("424a898b-ee13-441d-84de-ccb71343cf0d"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("2a317413-9179-4ab2-81a1-5054d546d5c5"),
                            RoleName = "User"
                        },
                        new
                        {
                            Id = new Guid("04edd7dc-4556-4575-b310-18f2f3115d11"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("f17d4f5f-2918-41b3-be09-29b7e293f824"),
                            RoleName = "User"
                        },
                        new
                        {
                            Id = new Guid("a7e70005-f39f-4b32-9878-49d9747c1214"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("38925b32-0803-489d-9855-84e331b44869"),
                            RoleName = "User"
                        },
                        new
                        {
                            Id = new Guid("d48d6d74-0bbb-4905-8d0c-b8ffa96571d5"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b98affcb-6a17-4ec4-a372-fa52102192b7"),
                            RoleName = "User"
                        },
                        new
                        {
                            Id = new Guid("556ff386-0e57-424d-b129-93dbf80cdbdd"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("57aca3fb-72f5-439d-82f6-16efc4183b9a"),
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("SmaguciaiDomain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmaguciaiDomain.Entities.User", b =>
                {
                    b.HasOne("SmaguciaiDomain.Entities.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmaguciaiDomain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmaguciaiDomain.Entities.Gender", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmaguciaiDomain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
